ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr

ARDUINO_LIBS  = SPI
BOARD_TAG     = mega2560
MONITOR_PORT  = /dev/ttyACM0

include /usr/share/arduino/Arduino.mk
